# Generated by Django 5.2.3 on 2025-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_participants', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('meetLink', models.URLField(blank=True, null=True)),
                ('instructor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='workshop_posters/')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseVideoLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
