# Generated by Django 5.2.3 on 2025-06-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_workshop_course_coursevideolink_course_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='time',
        ),
        migrations.AddField(
            model_name='workshop',
            name='dateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='registeredParticipants',
            field=models.IntegerField(default=0),
        ),
    ]
