# Generated by Django 5.2.3 on 2025-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_workshop_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.DurationField(),
        ),
    ]
