# Generated by Django 5.2.3 on 2025-06-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_workshop_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='dateAndTime',
        ),
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
