# Generated by Django 5.2.3 on 2025-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default=42, max_length=100),
            preserve_default=False,
        ),
    ]
