# Generated by Django 5.2.3 on 2025-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='numberOfRegisteredUsers',
            field=models.IntegerField(default=0),
        ),
    ]
