# Generated by Django 5.2.3 on 2025-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_course_numberofregisteredusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='course_posters/'),
        ),
    ]
