# Generated by Django 5.2.3 on 2025-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_workshop_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.FloatField(),
        ),
    ]
