# Generated by Django 5.2.3 on 2025-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_enrollment_courseenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
